### ISSUE TITLE
Ambiguity in the "name" placeholders on registration page

### ISSUE THREAD

**Issue by LizaKrokhina** [tanyabiryuk/LNUbiz#5]
Go to the "/signup" page. 

Both placeholders are named "Your name", what can confuse the user. 

Preferably should be changed to "first name/last name"

![зображення_2021-11-22_021112](https://user-images.githubusercontent.com/55539314/142784703-a9edce97-2470-44c8-981d-8d7beb3e7df4.png)

**Comment by olga210500** [comment]
Done
